# Site settings
title: Arun Ovireddiar Sundararajan

email: osarun@live.com.sg

description: > # this means to ignore newlines until "baseurl:"
  What is the purpose of this project?

baseurl: ""

url: "http://osarun.github.io/" # the base hostname & protocol for your site

twitter_username: arunos

github_username:  osarun

timezone: Asia/Singapore

# Build settings
markdown: kramdown
Pygments : true
